### ISSUE TITLE
Migrate mocha.opts to .mocharc.(json|js|yml|yaml)

### ISSUE THREAD

**Issue by munierujp** [secretlint/secretlint#125]
## Summary
This project has many `mocha.opts` files for Mocha, but it is deprecated from v7.0.0 [^1]
So, you should migrate `mocha.opts` files  to `.mocharc.(json|js|yml|yaml)` files.

As you know,  there is an unofficial but useful migration tool.

- [@azu/mocha-migrate](https://github.com/azu/mocha-migrate)

All you need is to run commands like below for each file.

```sh
# migarete
$ npx @azu/mocha-migrate migrate-opts -file /path/to/mocha.opts -type json -rm
# run test
$ yarn test
```

### Motivation
Make this project more modern.

[^1]: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#700--2020-01-05

**Comment by azu** [comment]
Yes. welcome to PR!

Tips: [`lerna exec`](https://github.com/lerna/lerna/tree/master/commands/exec) run a command in each package. It will help migration.

```
./node_modules/.bin/lerna exec --no-bail npx @azu/mocha-migrate migrate-opts -- -file test/mocha.opts -type json -rm
```
