### ISSUE TITLE
Not identifying AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by sanjeev-slalom** [secretlint/secretlint#149]
**What version of secretlint are you using?**
 
```
➤ npx secretlint --version
2.1.0
```

**What did you do? Please include the actual steps causing the issue.**

```
➤npm install lint-staged secretlint --save-dev

➤npx secretlint --init

➤npm install secretlint @secretlint/secretlint-rule-preset-recommend --save-dev

# Added a new file test.txt and update the secret access key
AWS_SECRET_KEY="<placeyoursecretkeyhere>"

# Run secretlint command. It doesn't find secretkey
➤npx secretlint "**/*"

However it works for below pattern. Notice that the secret in both did not change, but just the key. 
AWS_SECRET_ACCESS_KEY="<placeyoursecretkeyhere>"

  1:0  error  [AWSSecretAccessKey] found AWS Secret Access Key: <placeyoursecretkeyhere>  @secretlint/secretlint-rule-preset-recommend > @secretlint/secretlint-rule-aws
```

**What did you expect to happen?**
secretlint to identify the pattern with AWSSecretAccessKey

**What actually happened? Please include the actual, raw output from secretlint.**
No secrets found in the output

**Comment by sanjeev-slalom** [comment]
By looking at the source code, it looks like the pattern matching is very specific here https://github.com/secretlint/secretlint/blob/master/packages/%40secretlint/secretlint-rule-aws/src/index.ts#L104.

`// This Pattern match only `AWS?_SECRET_ACCESS_KEY=XXX``

Thoughts on adding a secret key pattern alone similar to `AWSAccessKeyIDPattern`? That would address issues when someone is defining the secret key value with a different key other than `AWS_SECRET_ACCESS_KEY`

**Comment by azu** [comment]
AWS's secret key has not suffix or postfix pattern like [slack](https://github.com/secretlint/secretlint/blob/6b0caa7f6eb728d8261637ae794482256c2ee68d/packages/%40secretlint/secretlint-rule-slack/src/index.ts#L47).
So, a secret key pattern alone will make false positive.
For example, `${QUOTE}([A-Za-z0-9/\+=]{40})${QUOTE}` will match non secret key value like `"012345678901234567890123456789"`.

We can take two approach.

1. Add pattern like `AWS_SECRET_KEY="<placeyoursecretkeyhere>"`
2. Verify the token like https://github.com/Yelp/detect-secrets/blob/624024ad5fd8a608e09ed719e5edab6ca95ef47e/detect_secrets/plugins/aws.py#L59 or GitHub's [secret scanning](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-secret-scanning)

📝 Current implementation is based on approach 1.

**Comment by sanjeev-slalom** [comment]
Sound good to me.
