### ISSUE TITLE
4.1.1 @secretlint/secretlint-rule-filter-comments not correctly released

### ISSUE THREAD

**Issue by roelandvanbatenburg** [secretlint/secretlint#208]
**What version of secretlint are you using?**
4.1.1

**What did you do? Please include the actual steps causing the issue.**

```
RUN apk add --no-cache npm && npm install -g secretlint @secretlint/secretlint-rule-preset-recommend
 ---> Running in dabed9c7f4a4
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/3) Installing c-ares (1.17.2-r0)
(2/3) Installing nodejs (14.17.6-r0)
(3/3) Installing npm (14.17.6-r0)
Executing busybox-1.32.1-r6.trigger
OK: 161 MiB in 67 packages
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @secretlint/secretlint-rule-filter-comments@^4.1.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@secretlint/secretlint-rule-preset-recommend'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-12T15_09_50_784Z-debug.log
The command '/bin/sh -c apk add --no-cache npm && npm install -g secretlint @secretlint/secretlint-rule-preset-recommend' returned a non-zero code: 1
```

**What did you expect to happen?**

Success

**What actually happened? Please include the actual, raw output from secretlint.**

See above.

From what I can see the 4.1.1 is not correctly released. See https://www.npmjs.com/package/@secretlint/secretlint-rule-filter-comments and then versions. It only lists 4.0.0. https://github.com/secretlint/secretlint/blob/v4.1.1/packages/%40secretlint/secretlint-rule-preset-recommend/package.json#L50 requires ^4.1.1

**Comment by azu** [comment]
Thanks for report!

Latest release of docker image has been failed. It may be related.
https://github.com/secretlint/secretlint/actions/runs/1328733462

**Comment by azu** [comment]
https://github.com/secretlint/secretlint/runs/3877346036?check_suite_focus=true
Something is wrong.
I try manual release
