### ISSUE TITLE
Move to lerna-lite

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#248]
This monorepo use lerna for publishing. However, lerna is maintenance mode.

- [docs: add maintenance note to README by inca · Pull Request #3092 · lerna/lerna](https://github.com/lerna/lerna/pull/3092)

We can move to lerna-lite that is alternative `lerna version` and `lerna publish` command

- [ghiscoding/lerna-lite: automate your workspace version & publish by using conventional-changelog-commits](https://github.com/ghiscoding/lerna-lite)

**Comment by azu** [comment]
Probably, we not need to use `lerna run` command.
Instead of it, We have used `turbo`.

**Comment by azu** [comment]
https://github.com/secretlint/secretlint/releases/tag/v5.2.0 works 🎉

**Comment by ghiscoding** [comment]
Hello again @azu, you might remember me as the developer who created the [Lerna-Lite](https://github.com/ghiscoding/lerna-lite) fork. I just released a new version [1.2.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.2.0) which brings support for pnpm/yarn `workspace:` protocol and thought you might be interested to give it a try? Feel free to reach out and thanks for all feedback and previous contributions. 

Cheers and happy coding 🎉
