### ISSUE TITLE
Install a package that handles sarif with Docker images

### ISSUE THREAD

**Issue by k-hal** [secretlint/secretlint#278]
## Summary

Allow Docker images to handle sarif format.

### Motivation

When using docker with github actions, use sarif to make code scanning easier to use.

**Comment by azu** [comment]
It is hard to extend existing docker image.
So, I agree that install sarif formatter as built-in docker image.


Probably, we can resolve this issue by adding `@secretlint/secretlint-formatter-sarif` into here
https://github.com/secretlint/secretlint/blob/032b3112823593ca3ce66bd40d6991b9eae74418/publish/docker/Dockerfile#L11
