### ISSUE TITLE
Add ability to extend the Dockerfile with more rules

### ISSUE THREAD

**Issue by slarwise** [secretlint/secretlint#380]
## Summary

I would like to be able to extend the Dockerfile to install more rules than the recommended rule set. Primarily, I would like to see `@secretlint/secretlint-rule-pattern` to be installed.

### Basic example

`publish/docker/Dockerfile` could be updated to something like this to install `@secretlint/secretlint-rule-pattern`. Or create an argument in the Dockerfile, something like `install-all` to install all available rules.

```diff
 COPY .secretlintrc.json $SECRETLINTRC
 RUN npm install -g secretlint@${SECRETLINT_VERSION} \
             @secretlint/secretlint-rule-preset-recommend@${SECRETLINT_VERSION} \
-            @secretlint/secretlint-formatter-sarif@latest && \
+            @secretlint/secretlint-formatter-sarif@latest \
+            @secretlint/secretlint-rule-pattern@${SECRETLINT_VERSION} && \
     rm -rf /usr/share/man /tmp/* \
            /root/.npm /root/.node-gyp \
            /usr/lib/node_modules/npm/man \
```

### Motivation

Running `secretlint` as a docker image is very easy to setup, particularly when used as a pre-commit hook. It would be very nice to be able to extend it with more rules so that we don't have to install it as an npm package when wanting to use more than the recommended rules.

**Comment by azu** [comment]
Or, We might want to add `@secretlint/secretlint-rule-pattern` to [@secretlint/secretlint-rule-preset-recommend](https://github.com/secretlint/secretlint/tree/master/packages/%40secretlint/secretlint-rule-preset-recommend) might be better added.
I've research ESLint, ESLint does not includes [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) which is similar `@secretlint/secretlint-rule-pattern` in recommended.

I'm ok that we add `@secretlint/secretlint-rule-pattern` to Dockerfile.

**Comment by slarwise** [comment]
Thanks for your fast reply, do you have a preference on those two options? I'm fine with either, and can get working on a PR.

**Comment by azu** [comment]
> we add `@secretlint/secretlint-rule-pattern` to Dockerfile.

I prefer this.

Welcome to PR!
