### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by slarwise** [secretlint/secretlint#386]
## Summary

A rule that detects Azure secrets. Can help out with PR if this sounds like a good idea.

### Basic example

A new npm package, something like `@secretlint/secretlint-rule-azure`.

### Motivation

Similar to the AWS rule, be able to detect Azure secrets in the code.

**Comment by azu** [comment]
I'm umfamilar with Azure.
Does Azure access token support prefix like `azure_xxxx`?
Or is it a featureless format?

Either way,　PR is welcome!
