### ISSUE TITLE
rule: .env 

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#66]
`.env` (dot env) is set of credential.
In sometimes, user commit this file by error.

We think about a rule for `.env`.

**Comment by azu** [comment]
is just `no-use-dot-env`?
And add relex option? 
- includes api_key, _token, entropy....

**Comment by azu** [comment]
We have decided that implment `no-dotenv` rule.

This rule is very simple

- if pass `.env` file, report error 

Because, dotenv document describe that

> Should I commit my .env file?
> No. We strongly recommend against committing your .env file to version control. It should only include environment-specific values such as database passwords or API keys. Your production database should have a different password than your development database.
> -- https://github.com/motdotla/dotenv#should-i-commit-my-env-file

We looking for implementor!

**Comment by azu** [comment]
`file` lifecyle file pass `source` object that includes `filePath`.
secretlint-rule-no-dotenv just check the filePath.

https://github.com/secretlint/secretlint/blob/master/docs/secretlint-rule.md

**Comment by munierujp** [comment]
Can I make it?

**Comment by azu** [comment]
Yeah! Welcome to PR!

**Comment by munierujp** [comment]
@azu I'll make it in `/packages/@secretlint/secretlint-rule-no-dotenv` directory, is that OK?

**Comment by azu** [comment]
@munierujp OK
