### ISSUE TITLE
The behavior of the `secretlintignore` option is a bit different from `gitignore`

### ISSUE THREAD

**Issue by ktmouk** [secretlint/secretlint#671]
**What version of secretlint are you using?**

7.0.7

**What did you do? Please include the actual steps causing the issue.**

The behavior of `secretlintignore` option is expected to be the same as that of `.gitignore` according to the [documentation](https://github.com/secretlint/secretlint/blob/master/docs/configuration.md#ignoring-files). However, when I add `foo` to the `.gitignore` file and  then pass it to `secretlintignore` option, it seems that Secretlint ignores `foo` directory, but does not ignore the `bar/foo` directory and its child files whereas the git command does.

**What did you expect to happen?**

I expect that Secretlint ignores all `foo` directories and files named `foo`, based on the [Git documentation](https://git-scm.com/docs/gitignore).

> ... For example, "**/foo" matches file or directory "foo" anywhere, **the same as pattern "foo"**.

**What actually happened? Please include the actual, raw output from secretlint.**

Secretlint does not ignore these files and directories.

**Workaround**

We can use `**/foo/**` instead of `foo` for a workaround, but fixing this issue is beneficial for users as we probably expect the same behavior from Secretlint as we do from the git command. 😃

**Comment by azu** [comment]
Related #337

**Comment by azu** [comment]
This issue will be fixed in https://github.com/secretlint/secretlint/releases/tag/v7.0.8

Please try it.

**Comment by ktmouk** [comment]
I confirmed that the logic works perfectly, thank you for fixing this issue!
